DROP DATABASE IF EXISTS tourpool;

CREATE DATABASE tourpool;

USE tourpool;

CREATE TABLE tours (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	tournaam VARCHAR(24) DEFAULT 'tour de france',
	jaar YEAR,
	startdatum DATE,
	einddatum DATE,
	created_at DATETIME DEFAULT now(),
	updated_at DATETIME ON UPDATE now()
);

CREATE TABLE etappes (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	tour_id INT NOT NULL,
	datum DATE,
	nummer SMALLINT,
	van VARCHAR(32),
	naar VARCHAR(32),
	afstand INT,
	rittype ENUM ('vlak', 'heuvels', 'bergen', 'ITT', 'PTT', '-'),
	created_at DATETIME DEFAULT now(),
	updated_at DATETIME ON UPDATE now(),
	FOREIGN KEY(tour_id)  REFERENCES tours(id)
);
CREATE TABLE rennerploegen (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ploegNaam VARCHAR(255),
	land VARCHAR(3),
	created_at DATETIME DEFAULT now(),
	updated_at DATETIME ON UPDATE now()
);
CREATE TABLE renners (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	vNaam VARCHAR(32),
	tNaam VARCHAR(16),
	aNaam VARCHAR(48),
	rNaam VARCHAR(48),
	created_at DATETIME DEFAULT now(),
	updated_at DATETIME ON UPDATE now()
); 

CREATE TABLE tourrenners (
	tour_id INT NOT NULL,
	renner_id INT NOT NULL,
	ploeg_id INT NOT NULL,
	nummer SMALLINT,
	FOREIGN KEY (tour_id) REFERENCES tours(id),
	FOREIGN KEY (renner_id)  REFERENCES renners(id),
	FOREIGN KEY (ploeg_id)  REFERENCES rennerploegen(id)
);

CREATE TABLE pools(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	naam VARCHAR(100) NOT NULL DEFAULT 'Jota Tourpool',
	tour_id INT,
	inleg DECIMAL(4,2),
	aantalRenners SMALLINT DEFAULT 10,
	aantalReserves SMALLINT DEFAULT 5,
	ritHoog DECIMAL(4,2) DEFAULT 2.5,
	ttlHoog DECIMAL(4,2) DEFAULT 1,
	ttlLaag DECIMAL(4,2) DEFAULT .1,
	inleverDatum DATETIME,
	created_at DATETIME DEFAULT now(),
	updated_at DATETIME ON UPDATE now(),
	FOREIGN KEY(tour_id) REFERENCES tours(id)
);
CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(32) NOT NULL UNIQUE,
	vNaam VARCHAR(32),
	tNaam VARCHAR(16),
	aNaam VARCHAR(48),	
	email VARCHAR(255) NOT NULL,
	isAdmin BOOL DEFAULT false,
	password VARCHAR(255) NOT NULL,
	created_at DATETIME DEFAULT now(),
	updated_at DATETIME ON UPDATE now()
);
CREATE TABLE userploegen (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	pool_id INT NOT NULL,
	ploegNaam VARCHAR(255),
	user_id INT NOT NULL,
	betaald BOOL,
	created_at DATETIME DEFAULT now(),
	updated_at DATETIME ON UPDATE now(),
	FOREIGN KEY(user_id) REFERENCES users(id),
	FOREIGN KEY(pool_id) REFERENCES pools(id)
);
CREATE TABLE userploegrenners (
	user_id INT NOT NULL,
	userploeg_id INT NOT NULL,
	renner_id INT NOT NULL,
	created_at DATETIME DEFAULT now(),
	updated_at DATETIME ON UPDATE now(),
	FOREIGN KEY(user_id) REFERENCES users(id),
	FOREIGN KEY(userploeg_id) REFERENCES userploegen(id),
	FOREIGN KEY(renner_id) REFERENCES renners(id)	
);
CREATE TABLE rituitslag(
	etappe_id INT NOT NULL,
	plaats SMALLINT NOT NULL,
	renner_id INT NOT NULL,
	created_at DATETIME DEFAULT now(),
	updated_at DATETIME ON UPDATE now(),
	FOREIGN KEY(etappe_id) REFERENCES etappes(id),
	FOREIGN KEY(renner_id) REFERENCES renners(id)
);

CREATE TABLE truienstand(
	etappe_id INT NOT NULL,
	trui ENUM('geel','rood','groen','wit','bol'),
	plaats SMALLINT NOT NULL,
	renner_id INT NOT NULL,
	created_at DATETIME DEFAULT now(),
	updated_at DATETIME ON UPDATE now(),
	FOREIGN KEY(etappe_id) REFERENCES etappes(id),
	FOREIGN KEY(renner_id) REFERENCES renners(id)
);
INSERT INTO tours (tournaam, jaar, startdatum, einddatum)
VALUES
( 'tour de france', 2023, '2023-07-01', '2023-07-23' );

INSERT INTO etappes ( nummer, tour_id, datum, van, naar, afstand, rittype)
VALUES
(1, 1, '2023-07-01', 'Bilbao', 'Bilbao', 182, 'heuvels'),
(2, 1, '2023-07-02', 'Vitoria-Gasteiz', 'San Sebastián', 182, 'heuvels'),
(3, 1, '2023-07-03', 'Amorebieta-Etxano', 'Bayonne', 185, 'vlak' ),
(4, 1, '2023-07-04', 'Dax', 'Nogaro', 182, 'vlak'), 
(5, 1, '2023-07-05', 'Pau', 'Laruns', 165, 'bergen'),
(6, 1, '2023-07-06', 'Tarbes', 'Cauterets', 145, 'bergen'), 
(7, 1, '2023-07-07', 'Mont-de-Marsan', 'Bordeaux', 170, 'vlak' ),
(8, 1, '2023-07-08', 'Libourne', 'Limoges', 201, 'heuvels' ), 
(9, 1, '2023-07-09', 'Saint-Léonard-de-Noblat', 'Puy de Dôme', 184, 'bergen' ),
(0, 1, '2023-07-10', 'rustdag', '-',0,'-'),
(10, 1, '2023-07-11', 'Saint-Ours-les-Roches', 'Issoire', 167, 'heuvels' ),
(11, 1, '2023-07-12', 'Clermont-Ferrand', 'Moulins', 180, 'vlak' ),
(12, 1, '2023-07-13', 'Roanne', 'Belleville-en-Beaujolais', 169, 'heuvels' ),
(13, 1, '2023-07-14', 'Châtillon-sur-Chalaronne','Grand Colombier',  138, 'bergen' ),
(14, 1, '2023-07-15', 'Annemasse', 'Morzine', 152, 'bergen' ),
(15, 1, '2023-07-16', 'Les Gets', 'Saint-Gervais Mont Blanc',180,  'bergen' ),
(0, 1, '2023-07-17', 'rustdag','-',  0, '-'),
(16, 1, '2023-07-18', 'Passy', 'Combloux', 22,'ITT'),  
(17, 1, '2023-07-19','Saint-Gervais Mont Blanc', 'Courchevel', 166, 'bergen' ), 
(18, 1, '2023-07-20', 'Moûtiers', 'Bourg-en-Bresse', 186, 'heuvels' ),
(19, 1, '2023-07-21', 'Moirans-en-Montagne', 'Poligny', 173, 'vlak' ), 
(20, 1, '2023-07-22', 'Belfort', 'Le Markstein', 133, 'bergen' ), 
(21, 1, '2023-07-23', 'Saint-Quentin-en-Yvelines', 'Parijs', 115, 'vlak' )
;

INSERT INTO pools(tour_id, inleg, aantalRenners, aantalReserves, ritHoog, ttlHoog, ttlLaag, inleverDatum) 
VALUES (1, 10, 10, 5, 2.5, 1, .1,'2023-06-25');

INSERT INTO rennerploegen (ploegnaam, land) 
VALUES 
('Israel-Premier Tech','ISR'),
('Uno-X Pro','NOR'),
('Lotto Dstny','BEL'),
('TotalEnergies','FRA'),
('AG2R Citroën Team','FRA'),
('Alpecin-Deceuninck','BEL'),
('Astana Qazaqstan Team','KAZ'),
('Bahrain - Victorious','BHR'),
('BORA - hansgrohe','DUI'),
('Cofidis','FRA'),
('EF Education-EasyPost','VS'),
('Groupama - FDJ','FRA'),
('INEOS Grenadiers','GBR'),
('Intermarché - Circus - Wanty','BEL'),
('Jumbo-Visma','NED'),
('Movistar Team','SPA'),
('Soudal - Quick Step','BEL'),
('Team Arkéa Samsic','FRA'),
('Team DSM','NED'),
('Team Jayco AlUla','AUS'),
('Trek - Segafredo','VS'),
('UAE Team Emirates','VAE')
;

INSERT INTO renners (vNaam, tNaam, aNaam) 
VALUES
("Tadej","","Pogacar"),  
("George","","Bennett"), 
("Mikkel","","Bjerg"),  
("Vegard","","Stake Laengen"),  
("Rafal","","Majka"),  
("Brandon","","Mcnulty"),  
("Marc","","Soler"),  
("Marc","","Hirschi"),  
("Primoz","","Roglic"),  
("Tiesj","","Benoot"),  
("Steven","","Kruijswijk"),  
("Sepp","","Kuss"),  
("Christophe","","Laporte"),  
("Wout","Van","Aert"),  
("Nathan","Van","Hooydonck"),  
("Jonas","","Vingegaard"),  
("Geraint","","Thomas"),  
("Daniel","","Felipe Martinez"),  
("Jonathan","","Castroviejo"),  
("Filippo","","Ganna"),  
("Thomas","","Pidcock"),  
("Luke","","Rowe"),  
("Dylan","van","Baarle"),  
("Adam","","Yates"),  
("Ben","","O'Connor"),  
("Geoffrey","","Bouchard"),  
("Mikaël","","Cherel"),  
("Benoit","","Cosnefroy"),  
("Stan","","Dewulf"),  
("Bob","","Jungels"),  
("Oliver","","Naesen"),  
("Aurélien","","Paret-Peintre"),  
("Aleksandr","","Vlasov"),  
("Felix","","Großschartner"),  
("Marco","","Haller"),  
("Lennard","","Kämna"),  
("Patrick","","Konrad"),  
("Nils","","Politt"),  
("Maximilian","","Schachmann"),  
("Danny","van","Poppel"),  
("Fabio","","Jakobsen"),  
("Kasper","","Asgreen"),  
("Andrea","","Bagioli"),  
("Mattia","","Cattaneo"),  
("Mikkel","","Frolich Honoré"),  
("Yves","","Lampaert"),  
("Michael","","Morkov"),  
("Florian","","Sénéchal"),  
("Enric","","Mas"),  
("Imanol","","Erviti"),  
("Gorka","","Izagirre"),  
("Matteo","","Jorgenson"),  
("Gregor","","Mühlberger"),  
("Nelson","","Oliveira"),  
("Albert","","Torres"),  
("Carlos","","Verona"),  
("Guillaume","","Martin"),  
("Pierre-Luc","","Périchon"),  
("Simon","","Geschke"),  
("Ion","","Izagirre"),  
("Victor","","Lafay"),  
("Anthony","","Perez"),  
("Benjamin","","Thomas"),  
("Max","","Walscheid"),  
("Jack","","Haig"),  
("Damiano","","Caruso"),  
("Kamil","","Gradek"),  
("Matej","","Mohoric"),  
("Luis","","Leon Sanchez"),  
("Dylan","","Teuns"),  
("Jan","","Tratnik"),  
("Fred","","Wright"),  
("David","","Gaudu"),  
("Antoine","","Duchesne"),  
("Kevin","","Geniets"),  
("Stefan","","Küng"),  
("Olivier","","Le Gac"),  
("Valentin","","Madouas"),  
("Thibaut","","Pinot"),  
("Michael","","Storer"),  
("Mathieu","van der","Poel"),  
("Silvan","","Dillier"),  
("Michael","","Gogl"),  
("Alexander","","Krieger"),  
("Jasper","","Philipsen"),  
("Edward","","Planckaert"),  
("Kristian","","Sbaragli"),  
("Guillaume","Van","Keirsbulck"),  
("Romain","","Bardet"),  
("Alberto","","Dainese"),  
("John","","Degenkolb"),  
("Nils","","Eekhoff"),  
("Chris","","Hamilton"),  
("Andreas","","Leknessund"),  
("Martijn","","Tusveld"),  
("Kevin","","Vermaerke"),  
("Alexander","","Kristoff"),  
("Sven Erik","","Bystrom"),  
("Kobe","","Goossens"),  
("Louis","","Meintjes"),  
("Andrea","","Pasqualon"),  
("Adrien","","Petit"),  
("Taco","van der","Hoorn"),  
("Georg","","Zimmermann"),  
("Alexey","","Lutsenko"),  
("Alexandr","","Riabushenko"),  
("Joe","","Dombrowski"),  
("Fabio","","Felline"),  
("Dmitriy","","Gruzdev"),  
("Gianni","","Moscon"),  
("Simone","","Velasco"),  
("Andrey","","Zeits"),  
("Rigoberto","","Uran"),  
("Ruben","","Guerreiro"),  
("Alberto","","Bettiol"),  
("Stefan","","Bissegger"),  
("Owain","","Doull"),  
("Magnus","","Cort"),  
("Neilson","","Powless"),  
("Jonas","","Rutsch"),  
("Nairo","","Quintana"),  
("Warren","","Barguil"),  
("Maxime","","Bouet"),  
("Amaury","","Capiot"),  
("Hugo","","Hofstetter"),  
("Matis","","Louvel"),  
("Lukasz","","Owsian"),  
("Connor","","Swift"),  
("Caleb","","Ewan"),  
("Frederik","","Frison"),  
("Philippe","","Gilbert"),  
("Reinardt","","Janse Van Rensburg"),  
("Andreas","","Kron"),  
("Brent","Van","Moer"),  
("Florian","","Vermeersch"),  
("Tim","","Wellens"),  
("Mads","","Pedersen"),  
("Giulio","","Ciccone"),  
("Tony","","Gallopin"),  
("Alex","","Kirsch"),  
("Bauke","","Mollema"),  
("Quinn","","Simmons"),  
("Toms","","Skujins"),  
("Jasper","","Stuyven"),  
("Peter","","Sagan"),  
("Edvald","","Boasson Hagen"),  
("Maciej","","Bodnar"),  
("Mathieu","","Burgaudeau"),  
("Pierre","","Latour"),  
("Daniel","","Oss"),  
("Anthony","","Turgis"),  
("Alexis","","Vuillermoz"),  
("Chris","","Froome"),  
("Guillaume","","Boivin"),  
("Simon","","Clarke"),  
("Jakob","","Fuglsang"),  
("Guy","","Niv"),  
("Hugo","","Houle"),  
("Krists","","Neilands"),  
("Michael","","Woods"),  
("Michael","","Matthews"),  
("Jack","","Bauer"),  
("Luke","","Durbridge"),  
("Dylan","","Groenewegen"),  
("Amund","","Grondahl Jansen"),  
("Christopher","","Juul-Jensen"),  
("Luka","","Mezgec"),  
("Nick","","Schultz"),  
("Franck","","Bonnamour"),  
("Cyril","","Barthe"),  
("Alexis","","Gougeard"),  
("Jérémy","","Lecroq"),  
("Cyril","","Lemoine"),  
("Luca","","Mozzato"),  
("Pierre","","Rolland"),  
("Sebastian","","Schönberger")
;

UPDATE renners SET rNaam = CONCAT(aNaam,",", SUBSTRING(vNaam, 1,1), '. ', tNaam);
